// BASE DE DATOS DE EVENTOS (real). Editá este archivo para sumar, corregir o borrar programas.
// Cada evento es un bloque { ... }. Las imágenes van en la misma carpeta que index.html y se citan como "nombre.jpg".
window.PD_EVENTS = [
  {
    "id": "eco-armonic-volver-2026-09-19",
    "titulo": "Eco Armonic: Volver",
    "fecha": "2026-09-19",
    "hora": "11:00",
    "lugar": "Espacio Hesai, Delta",
    "zona": "GBA Norte",
    "categoria": "Taller y comunidad",
    "precio": "$60.000 (Full Experience)",
    "descripcion": "Un día en una isla del Delta para bajar el ruido y desconectar: yoga, respiración, cristales, ecstatic dance y sunset, de 11 a 19 hs. Sin alcohol. Full Experience $60.000 (incluye lancha, comida/bebida y todas las actividades); $45.000 con traslado ida y vuelta. Lanchas 11:30 y 12:30 (la de 10:30 agotada). Últimos cupos.",
    "link": "https://www.instagram.com/eco.armonic/",
    "organizador": "Eco Armonic",
    "flyer": "eco-armonic-volver.jpg",
    "origen": "chat"
  },
  {
    "id": "linea-caliente-primavera-2026-09-19",
    "titulo": "Línea Caliente en La Nube: Festival de Primavera",
    "fecha": "2026-09-19",
    "hora": "16:00",
    "lugar": "La Nube, Costanera",
    "zona": "CABA",
    "categoria": "Fiesta y música",
    "precio": "",
    "descripcion": "Festival de primavera con horario extendido, de 16 a 04 hs. Line-up: Alot, Pabels, Stump Valley, Juna, Balaciano, Nebula Estudio, Slot, Harari, KSSLR y Tres. Código de descuento: CALIENTECALIENTE.",
    "link": "",
    "organizador": "Línea Caliente y La Nube",
    "flyer": "linea-caliente-la-nube.jpg",
    "origen": "chat"
  },
  {
    "id": "filosofia-a-la-carta-11-2026-09-19",
    "titulo": "Filosofía a la Carta: Conspiración y paranoia",
    "fecha": "2026-09-19",
    "hora": "19:00",
    "lugar": "Bruce Wine, Perú 653, San Telmo",
    "zona": "CABA",
    "categoria": "Arte y cultura",
    "precio": "Entrada con copa de vino",
    "descripcion": "Onceavo Encuentro de Filosofía a la Carta, edición aniversario. DJs de 19 a 21 hs, charla de 21 a 23 hs con Mauricio Vera, Aaron Marco, Unai Rivas Campo y Fran Cus, y DJs hasta la 1. Cupos limitados: reservá tu copa en Ágora.",
    "link": "https://agora.red/brucewine/eventos/onceavo-encuentro-de-filosofia-a-la-carta",
    "organizador": "Bruce Wine",
    "flyer": "filosofia-a-la-carta.jpg",
    "origen": "chat"
  },
  {
    "id": "dobro-disco-2026-09-19",
    "titulo": "Dobro Disco: fiesta balcánica",
    "fecha": "2026-09-19",
    "hora": "20:00",
    "lugar": "Chile al 1400, Monserrat",
    "zona": "CABA",
    "categoria": "Fiesta y música",
    "precio": "",
    "descripcion": "Primera edición de una fiesta de música balcánica y sonidos de Europa del Este: DJ set, visuales, ambientación, intervenciones y sorpresas, de 20 a 00 hs. Cupos limitados, entradas anticipadas a precio de lanzamiento. Tu entrada es tu visa.",
    "link": "https://dobro-disco.com.ar/",
    "organizador": "Dobro Disco",
    "flyer": "dobro-disco.jpg",
    "origen": "chat"
  },
  {
    "id": "fractions-grace-badlove-2026-09-19",
    "titulo": "Fractions: Grace & Badlove en The Lift",
    "fecha": "2026-09-19",
    "hora": "20:00",
    "lugar": "The Lift, Godoy Cruz 1967, Palermo",
    "zona": "CABA",
    "categoria": "Fiesta y música",
    "precio": "Desde $12.000",
    "descripcion": "Grace & Badlove presentan Fractions, su tercer disco de estudio, en vivo: del funky disco al soul y un bolero. De 20 a 23:30 hs, capacidad limitada. Código de descuento que compartió la banda en el grupo: LIVESESSIONS-50%OFF.",
    "link": "https://www.passline.com/eventos/fractions-x-grace-badlove",
    "organizador": "The Lift",
    "flyer": "fractions-grace-badlove.jpg",
    "origen": "chat"
  },
  {
    "id": "el-remolon-brawlio-lalala-2026-09-19",
    "titulo": "El Remolón & Brawlio + La Sacer en Lalalá",
    "fecha": "2026-09-19",
    "hora": "22:00",
    "lugar": "Lalalá, Av. Álvarez Thomas 1541, Villa Ortúzar",
    "zona": "CABA",
    "categoria": "Fiesta y música",
    "precio": "Desde $8.000",
    "descripcion": "El Remolón y Brawlio vuelven a tocar en Buenos Aires después de su gira europea, con La Sacer en la música y visuales de Logicanalogica. Show + fiesta, de 22 a 02 hs. Anticipada promocional $8.000, general $10.000.",
    "link": "https://www.passline.com/eventos/199-el-remolon-brawlio-la-sacer-vj-logicaanalogica-show-fiesta-fertil-discos",
    "organizador": "Lalalá y Fértil Discos",
    "flyer": "el-remolon-brawlio.jpg",
    "origen": "chat"
  },
  {
    "id": "audiokidz-dune-park-2026-09-20",
    "titulo": "Audiokidz en Dune Park",
    "fecha": "2026-09-20",
    "hora": "16:00",
    "lugar": "Dune Park, Aráoz 740",
    "zona": "CABA",
    "categoria": "Fiesta y música",
    "precio": "Entradas agotadas",
    "descripcion": "Propuesta de Audioholics para que chicos y chicas descubran la música electrónica en familia: workshops de DJing y producción, experiencias de arte y tecnología y una fiesta con line-up de niños y niñas. Los menores ingresan siempre con un adulto responsable.",
    "link": "https://www.ondadirect.com/es/event/audiokidz",
    "organizador": "Audioholics y Dune Park",
    "flyer": "audiokidz.jpg",
    "origen": "chat"
  },
  {
    "id": "circulo-de-cacao-nunez-2026-09-20",
    "titulo": "Círculo de cacao: ritual del equinoccio de primavera",
    "fecha": "2026-09-20",
    "hora": "",
    "lugar": "Núñez (dirección a consultar con la organizadora)",
    "zona": "CABA",
    "categoria": "Taller y comunidad",
    "precio": "A la gorra",
    "descripcion": "Círculo de cacao y ceremonial maya para recibir la primavera. Ritual del equinoccio. A la gorra. El contacto para consultas y la dirección figuran en el flyer.",
    "link": "",
    "organizador": "Nathaji Holística y Minesve",
    "flyer": "circulo-de-cacao.jpg",
    "origen": "chat"
  },
  {
    "id": "vuelan-las-sisters-2026-09-25",
    "titulo": "Vuelan las Sisters",
    "fecha": "2026-09-25",
    "hora": "20:00",
    "lugar": "Barracas (dirección por privado)",
    "zona": "CABA",
    "categoria": "Fiesta y música",
    "precio": "$8.000 anticipada / $10.000 puerta",
    "descripcion": "Fecha de Vuelan las Blussas y Sisters Triangla, hecha por y para mujeres, personas trans y no binaries. Empieza con un conversatorio y sigue con una electrojam de luxe (Luz Electra, Persefone Dai, Van Shake, Ani Soul, Juana Ines Cortafierros, Maia Koenig, Viejalok y más). Cierra La Brianne. Feria, masajes y tarot. Capacidad limitada.",
    "link": "",
    "organizador": "Vuelan las Blussas y Sisters Triangla",
    "flyer": "vuelan-las-sisters.jpg",
    "origen": "chat"
  },
  {
    "id": "casa-kumo-the-gallery-2026-09-27",
    "titulo": "Casa Kumo: The Gallery",
    "fecha": "2026-09-27",
    "hora": "15:00",
    "lugar": "Casa Kumo, Av. Juan B. Justo 807",
    "zona": "CABA",
    "categoria": "Feria y mercado",
    "precio": "$5.000",
    "descripcion": "Una selección de todo lo que nos gusta, en la terraza de Casa: mobiliario, joyería, accesorios, fotografía, tattoos, ropa, café, parrilla y vermú, con DJ. Con Agujero Mob, Studio Jotade, Amalia Handcraft, Paloma Montagne, Lu Rosso, Cougar_tv, Foca, Asado Campero, Alfonsina y Micu JS. De 15 a 19 hs. Con la entrada, 2x1 en vermú. Acceso por escalera.",
    "link": "https://enter.ar/eventos/casa-kumo-the-gallery-2",
    "organizador": "Casa Kumo",
    "flyer": "casa-kumo-the-gallery.jpg",
    "origen": "chat"
  },
  {
    "id": "arte-activa-abracadabra-2026-10-03",
    "titulo": "Arte Activa 2026: edición Abracadabra",
    "fecha": "2026-10-03",
    "hora": "18:00",
    "lugar": "Sede de Fuego Austral, Paz Soldán 5150, Paternal",
    "zona": "CABA",
    "categoria": "Arte y cultura",
    "precio": "Bono desde $15.000",
    "descripcion": "Evento autogestionado por la comunidad para recaudar fondos y llevar el arte de Buenos Aires a Fuego Austral 2027. Juegos, intervenciones artísticas, música de la comunidad, comida y bebida. De 18 a 03 hs, puerta hasta las 23. Bono Hocus Pocus $15.000 (en puerta $20.000).",
    "link": "https://eventos.fuegoaustral.org/",
    "organizador": "Fuego Austral",
    "flyer": "arte-activa.jpg",
    "origen": "chat"
  },
  {
    "id": "corona-sunsets-2026-10-17",
    "titulo": "Corona Sunsets Buenos Aires",
    "fecha": "2026-10-17",
    "hora": "16:30",
    "lugar": "Ciudad Universitaria",
    "zona": "CABA",
    "categoria": "Fiesta y música",
    "precio": "",
    "descripcion": "Con Danny Tenaglia, Lee Burridge, Chris Schwarzwälder y Mandrake. Capacidad limitada, solo mayores de 18. Máximo 4 tickets por persona; al ingresar piden el QR de Enigma y DNI.",
    "link": "https://www.enigmatickets.com/event/e4f5683d-7f06-44b0-a398-de8418d5e359",
    "organizador": "Buena Productora",
    "flyer": "corona-sunsets.jpg",
    "origen": "chat"
  },
  {
    "id": "muestra-intad-cat-2026-11-13",
    "titulo": "Muestra final del Laboratorio de Tecnología Interactiva para la Escena",
    "fecha": "2026-11-13",
    "hora": "18:30",
    "lugar": "Estudio C.A.T., Chacabuco 974",
    "zona": "CABA",
    "categoria": "Arte y cultura",
    "precio": "",
    "descripcion": "Muestra final abierta al público del laboratorio de InTAD y el Estudio C.A.T. sobre el cruce entre movimiento y tecnología digital interactiva.",
    "link": "",
    "organizador": "InTAD y Estudio C.A.T.",
    "flyer": "",
    "origen": "chat"
  }
];
